name: digte
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pyyaml
  - numpy
  - jsonlines
  - tqdm
  - requests
  - packaging
  - typing_extensions
  - pip:
      - torch>=2.0
      - transformers>=4.40
      - datasets
      - huggingface_hub
